zsck:
  default-uid: 131649477
  permit:
    is-init: true
    owner: ${custom.owner_number}
  academic:
    user-name: ${custom.academic.username}
    password: ${custom.academic.password}
  kugou:
    enable-local: false
    remote-url-prefix: http://www.wolves.vip/music
    add-music-mapping: /add



logging:
  level:
    com.zsck: info

spring:
  profiles:
    include: dev
  aop:
    auto: false
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://${custom.mysql.host}:${custom.mysql.port}/my_class
          username: ${custom.mysql.username}
          password: ${custom.mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            initial-size: 5
            min-idle: 5
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 30000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: true
            test-on-return: false
        music:
          url: jdbc:mysql://${custom.mysql.host}:${custom.mysql.port}/web
          username: ${custom.mysql.username}
          password: ${custom.mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            initial-size: 5
            min-idle: 5
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 30000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: true
            test-on-return: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl